// console.log("Hello welcome");
var general;
console.log(general);
general=6;
console.log(typeof general);
general='hi';
console.log(typeof general);
general="hi";
console.log(typeof general);
general=true;
console.log(typeof general);
general=null;
console.log(typeof general);
general=[1,2,3,4];
console.log(typeof general);
console.log(general.length);
console.log(2+3);
console.log("Hi"+" welcome");
console.log(2+" hi");
